In [295]:
import pandas as pd
#Intent Detection Model using CNN
import tensorflow as tf
tf.__version__

'2.17.0-dev20240605'

In [297]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [299]:
df = pd.read_csv('yelp.csv')

In [301]:
df

,business_id,date,review_id,stars,text,type,user_id,cool,useful,funny
0,9yKzy9PApeiPPOUJEtnvkg,2011-01-26,fWKvX83p0-ka4JS3dc6E5A,5,My wife took me here on my birthday for breakf...,review,rLtl8ZkDX5vH5nAx9C3q5Q,2,5,0
1,ZRJwVLyzEJq1VAihDhYiow,2011-07-27,IjZ33sJrzXqU-0X6U8NwyA,5,I have no idea why some people give bad review...,review,0a2KyEL0d3Yb1V6aivbIuQ,0,0,0
2,6oRAC4uyJCsJl1X0WZpVSA,2012-06-14,IESLBzqUCLdSzSqm0eCSxQ,4,love the gyro plate. Rice is so good and I als...,review,0hT2KtfLiobPvh6cDC8JQg,0,1,0
3,_1QQZuf4zZOyFCvXc0o6Vg,2010-05-27,G-WvGaISbqqaMHlNnByodA,5,"Rosie, Dakota, and I LOVE Chaparral Dog Park!!...",review,uZetl9T0NcROGOyFfughhg,1,2,0
4,6ozycU1RpktNG2-1BroVtw,2012-01-05,1uJFq2r5QfJG_6ExMRCaGw,5,General Manager Scott Petello is a good egg!!!...,review,vYmM4KTsC8ZfQBg-j5MWkw,0,0,0
...,...,...,...,...,...,...,...,...,...,...
9995,VY_tvNUCCXGXQeSvJl757Q,2012-07-28,Ubyfp2RSDYW0g7Mbr8N3iA,3,First visit...Had lunch here today - used my G...,review,_eqQoPtQ3e3UxLE4faT6ow,1,2,0
9996,EKzMHI1tip8rC1-ZAy64yg,2012-01-18,2XyIOQKbVFb6uXQdJ0RzlQ,4,Should be called house of deliciousness!\n\nI ...,review,ROru4uk5SaYc3rg8IU7SQw,0,0,0
9997,53YGfwmbW73JhFiemNeyzQ,2010-11-16,jyznYkIbpqVmlsZxSDSypA,4,I recently visited Olive and Ivy for business ...,review,gGbN1aKQHMgfQZkqlsuwzg,0,0,0
9998,9SKdOoDHcFoxK5ZtsgHJoA,2012-12-02,5UKq9WQE1qQbJ0DJbc-B6Q,2,My nephew just moved to Scottsdale recently so...,review,0lyVoNazXa20WzUyZPLaQQ,0,0,0
9999,pF7uRzygyZsltbmVpjIyvw,2010-10-16,vWSmOhg2ID1MNZHaWapGbA,5,4-5 locations.. all 4.5 star average.. I think...,review,KSBFytcdjPKZgXKQnYQdkA,0,0,0

In [303]:
df = df[['text', 'stars']]

In [305]:
df['label'] = df['stars'].apply(lambda x: 'Sad' if x < 3 else 'Happy')

/var/folders/4w/nfkvhvrs0sxd55472ytdz0nh0000gp/T/ipykernel_8295/3819513822.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = df['stars'].apply(lambda x: 'Sad' if x < 3 else 'Happy')

In [307]:
df.drop(['stars'], axis=1, inplace=True)

/var/folders/4w/nfkvhvrs0sxd55472ytdz0nh0000gp/T/ipykernel_8295/3206604362.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['stars'], axis=1, inplace=True)

In [309]:
df

                                                   text  label
0     My wife took me here on my birthday for breakf...  Happy
1     I have no idea why some people give bad review...  Happy
2     love the gyro plate. Rice is so good and I als...  Happy
3     Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  Happy
4     General Manager Scott Petello is a good egg!!!...  Happy
...                                                 ...    ...
9995  First visit...Had lunch here today - used my G...  Happy
9996  Should be called house of deliciousness!\n\nI ...  Happy
9997  I recently visited Olive and Ivy for business ...  Happy
9998  My nephew just moved to Scottsdale recently so...    Sad
9999  4-5 locations.. all 4.5 star average.. I think...  Happy

[10000 rows x 2 columns]

In [311]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    10000 non-null  object
 1   label   10000 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB

In [313]:
df['label'].value_counts()

label
Happy    8324
Sad      1676
Name: count, dtype: int64

In [315]:
label = df['label'].map({'Happy': 1, 'Sad': 0})

In [317]:
label

0       1
1       1
2       1
3       1
4       1
       ..
9995    1
9996    1
9997    1
9998    0
9999    1
Name: label, Length: 10000, dtype: int64

In [319]:
#Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(message, label, test_size=0.2, random_state=42)

In [321]:
# For Tokenization
from tensorflow.keras.preprocessing.text import Tokenizer

#Decide the Vocabulary Word Frequency Size

vocabFreqWordSize = None

# If the word 'spiderman' exists a minimum of num_words times in the corpus,
# then it will be added in the vocab dictionary

#Convert the sentences into sequence of words

tokenizer = Tokenizer(num_words=vocabFreqWordSize)

#Fit the training data

tokenizer.fit_on_texts(X_train)

In [323]:
#Lets create the sequence objects

seq_train = tokenizer.texts_to_sequences(X_train)
seq_test = tokenizer.texts_to_sequences(X_test)

In [325]:
#Lets pad the sequence data
#This creates a matrix where the
# rows = Documents
# Cols = Time Steps (For our understanding its the vocab with padding)

from tensorflow.keras.preprocessing.sequence import pad_sequences

trainData = pad_sequences(seq_train)
T = trainData.shape[1]
T

500

In [327]:
trainData.shape

(8000, 500)

In [329]:
testData = pad_sequences(seq_test , maxlen=T)
testData.shape

(2000, 500)

In [331]:
#Build the Model
#Question: Can we use ANN?
#Answer: We can use ANN if the dataset is small. BUt preferred is CNN due to data size and avoiding memory overflow issue
# and without compromising the quality of the data.

In [333]:
#Get the Vocab Size of the Tokenizer
V = len(tokenizer.word_index)

In [460]:
#CNN for Text data -- Conv1D



from tensorflow.keras.layers import Dense,Input,Conv1D,Embedding,MaxPooling1D,GlobalMaxPooling1D
from tensorflow.keras.models import Model

model = Sequential([
    Embedding(input_dim=V+1, output_dim=128, input_length=T),
    Conv1D(filters=128, kernel_size=5, activation='relu'),
    GlobalMaxPooling1D(),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

/Users/dzaytsev/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [462]:
#Compile
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [464]:
model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_20 (Embedding)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_32 (Conv1D)              │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_max_pooling1d_20         │ ?                      │   0 (unbuilt) │
│ (GlobalMaxPooling1D)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_13 (Dropout)            │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_35 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_36 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [466]:
#Train
history = model.fit(trainData, y_train, epochs=5, validation_data=(testData,y_test))

Epoch 1/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 19ms/step - accuracy: 0.8153 - loss: 0.4688 - val_accuracy: 0.8870 - val_loss: 0.2806
Epoch 2/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step - accuracy: 0.8993 - loss: 0.2526 - val_accuracy: 0.8910 - val_loss: 0.2665
Epoch 3/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step - accuracy: 0.9621 - loss: 0.1091 - val_accuracy: 0.8940 - val_loss: 0.3665
Epoch 4/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step - accuracy: 0.9849 - loss: 0.0473 - val_accuracy: 0.8945 - val_loss: 0.3984
Epoch 5/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step - accuracy: 0.9936 - loss: 0.0192 - val_accuracy: 0.8905 - val_loss: 0.4898

In [468]:
def get_intent(pred):
    if np.average(pred) >= 0.5:
        return 'HAPPY :)'
    else:
        return 'SAD :('

In [470]:
user_input = input("Enter a message to classify: ")
seq_input = tokenizer.texts_to_sequences(user_input)
seq_input_pad = pad_sequences(seq_input, maxlen=T)
prediction = model.predict(seq_input_pad)


print("This message intent is:", get_intent(prediction))

Enter a message to classify:  I feel good today

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
This message intent is: HAPPY :)

In [480]:
user_input = input("Enter a message to classify: ")
seq_input = tokenizer.texts_to_sequences(user_input)
seq_input_pad = pad_sequences(seq_input, maxlen=T)
prediction = model.predict(seq_input_pad)


print("This message intent is:", get_intent(prediction))

Enter a message to classify:  bad bad bad, worst ever!

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
This message intent is: HAPPY :)

In [482]:
prediction

array([[0.79324424],
       [0.4691457 ],
       [0.4691457 ],
       [0.4691457 ],
       [0.79324424],
       [0.4691457 ],
       [0.4691457 ],
       [0.4691457 ],
       [0.79324424],
       [0.4691457 ],
       [0.4691457 ],
       [0.4691457 ],
       [0.4691457 ],
       [0.65742904],
       [0.5288125 ],
       [0.56750476],
       [0.4691457 ],
       [0.5893615 ],
       [0.4691457 ],
       [0.49063957],
       [0.52131414],
       [0.49063957],
       [0.56750476],
       [0.4691457 ]], dtype=float32)