In [ ]:
# Install Viz Tool for LDA algorithm
! pip install pyLDAvis

Collecting pyLDAvis
  Downloading pyLDAvis-3.4.1-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: numpy>=1.24.2 in /usr/local/lib/python3.10/dist-packages (from pyLDAvis) (1.26.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from pyLDAvis) (1.13.1)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from pyLDAvis) (2.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from pyLDAvis) (1.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from pyLDAvis) (3.1.4)
Requirement already satisfied: numexpr in /usr/local/lib/python3.10/dist-packages (from pyLDAvis) (2.10.1)
Collecting funcy (from pyLDAvis)
  Downloading funcy-2.0-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from pyLDAvis) (1.3.2)
Requirement already satisfied: gensim in /usr/local/lib/python3.10/dist-packages (from pyLDAvis) (4.3.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from pyLDAvis) (71.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0.0->pyLDAvis) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0.0->pyLDAvis) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0.0->pyLDAvis) (2024.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.0.0->pyLDAvis) (3.5.0)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from gensim->pyLDAvis) (7.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->pyLDAvis) (2.1.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->pyLDAvis) (1.16.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from smart-open>=1.8.1->gensim->pyLDAvis) (1.16.0)
Downloading pyLDAvis-3.4.1-py3-none-any.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 32.8 MB/s eta 0:00:00
Downloading funcy-2.0-py2.py3-none-any.whl (30 kB)
Installing collected packages: funcy, pyLDAvis
Successfully installed funcy-2.0 pyLDAvis-3.4.1

In [ ]:
#Load the dataset
from sklearn.datasets import fetch_20newsgroups
newsgroups = fetch_20newsgroups(remove=('headers','footers','quotes'))
docs_raw = newsgroups.data
print(len(docs_raw))

11314

In [ ]:
# Ref: https://scikit-learn.org/stable/datasets/real_world.html

In [ ]:
docs_raw

['I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.',
 "A fair number of brave souls who upgraded their SI clock oscillator have\nshared their experiences for this poll. Please send a brief message detailing\nyour experiences with the procedure. Top speed attained, CPU rated speed,\nadd on cards and adapters, heat sinks, hour of usage per day, floppy disk\nfunctionality with 800 and 1.4 m floppies are especially requested.\n\nI will be summarizing in the next two days, so please add to the network\nknowledge base if you have done the clock upgrade and haven't answered this\npoll. Thanks.",
 'well folks, my mac plus finally gave up the ghost this weekend after\nstarting life as a 512k way back in 1985.  sooo, i\'m in the market for a\nnew machine a bit sooner than i intended to be...\n\ni\'m looking into picking up a powerbook 160 or maybe 180 and have a bunch\nof questions that (hopefully) somebody can answer:\n\n* does anybody know any dirt on when the next round of powerbook\nintroductions are expected?  i\'d heard the 185c was supposed to make an\nappearence "this summer" but haven\'t heard anymore on it - and since i\ndon\'t have access to macleak, i was wondering if anybody out there had\nmore info...\n\n* has anybody heard rumors about price drops to the powerbook line like the\nones the duo\'s just went through recently?\n\n* what\'s the impression of the display on the 180?  i could probably swing\na 180 if i got the 80Mb disk rather than the 120, but i don\'t really have\na feel for how much "better" the display is (yea, it looks great in the\nstore, but is that all "wow" or is it really that good?).  could i solicit\nsome opinions of people who use the 160 and 180 day-to-day on if its worth\ntaking the disk size and money hit to get the active display?  (i realize\nthis is a real subjective question, but i\'ve only played around with the\nmachines in a computer store breifly and figured the opinions of somebody\nwho actually uses the machine daily might prove helpful).\n\n* how well does hellcats perform?  ;)\n\nthanks a bunch in advance for any info - if you could email, i\'ll post a\nsummary (news reading time is at a premium with finals just around the\ncorner... :( )\n--\nTom Willis  \\  twillis@ecn.purdue.edu    \\    Purdue Electrical Engineering',
 "\nDo you have Weitek's address/phone number?  I'd like to get some information\nabout this chip.\n",
 "From article <C5owCB.n3p@world.std.com>, by tombaker@world.std.com (Tom A Baker):\n\n\nMy understanding is that the 'expected errors' are basically\nknown bugs in the warning system software - things are checked\nthat don't have the right values in yet because they aren't\nset till after launch, and suchlike. Rather than fix the code\nand possibly introduce new bugs, they just tell the crew\n'ok, if you see a warning no. 213 before liftoff, ignore it'.",
 '\n\n\n\n\nOf course.  The term must be rigidly defined in any bill.\n\n\nI doubt she uses this term for that.  You are using a quote allegedly\nfrom her, can you back it up?\n\n\n\n\nI read the article as presenting first an argument about weapons of mass\ndestruction (as commonly understood) and then switching to other topics.\nThe first point evidently was to show that not all weapons should be\nallowed, and then the later analysis was, given this understanding, to\nconsider another class.\n\n\n\n',
 'There were a few people who responded to my request for info on\ntreatment for astrocytomas through email, whom I couldn\'t thank\ndirectly because of mail-bouncing probs (Sean, Debra, and Sharon).  So\nI thought I\'d publicly thank everyone.\n\nThanks! \n\n(I\'m sure glad I accidentally hit "rn" instead of "rm" when I was\ntrying to delete a file last September. "Hmmm... \'News?\' What\'s\nthis?"....)',
 '                                                                      \nALL this shows is that YOU don\'t know much about SCSI.\n\nSCSI-1 {with a SCSI-1 controler chip} range is indeed 0-5MB/s\nand that is ALL you have right about SCSI\nSCSI-1 {With a SCSI-2 controller chip}: 4-6MB/s with 10MB/s burst {8-bit}\n Note the INCREASE in SPEED, the Mac Quadra uses this version of SCSI-1\n so it DOES exist. Some PC use this set up too.\nSCSI-2 {8-bit/SCSI-1 mode}:          4-6MB/s with 10MB/s burst\nSCSI-2 {16-bit/wide or fast mode}:  8-12MB/s with 20MB/s burst\nSCSI-2 {32-bit/wide AND fast}:     15-20MB/s with 40MB/s burst\n \nBy your OWN data the "Although SCSI is twice as fast as ESDI" is correct\nWith a SCSI-2 controller chip SCSI-1 can reach 10MB/s which is indeed\n"20% faster than IDE" {120% of 8.3 is 9.96}. ALL these SCSI facts have been\nposted to this newsgroup in my Mac & IBM info sheet {available by FTP on \nsumex-aim.stanford.edu (36.44.0.6) in the info-mac/report as \nmac-ibm-compare[version #].txt (It should be 173 but 161 may still be there)}\n\nPart of this problem is both Mac and IBM PC are inconsiant about what SCSI\nis which.  Though it is WELL documented that the Quadra has a SCSI-2 chip\nan Apple salesperson said "it uses a fast SCSI-1 chip" {Not at a 6MB/s,\n10MB/s burst it does not. SCSI-1 is 5MB/s maximum synchronous and Quadra\nuses ANsynchronous SCSI which is SLOWER}  It seems that Mac and IBM see\nSCSI-1 interface and think \'SCSI-1\' when it maybe a SCSI-1 interface driven\nin the machine by a SCSi-2 controller chip in 8-bit mode {Which is MUCH\nFASTER then true SCSI-1 can go}.',
 'I have win 3.0 and downloaded several icons and BMP\'s but I can\'t figure out\nhow to change the "wallpaper" or use the icons.  Any help would be appreciated.\n\n\nThanx,\n\n-Brando',
 "\n\n\nI've had the board for over a year, and it does work with Diskdoubler,\nbut not with Autodoubler, due to a licensing problem with Stac Technologies,\nthe owners of the board's compression technology. (I'm writing this\nfrom memory; I've lost the reference. Please correct me if I'm wrong.)\n\nUsing the board, I've had problems with file icons being lost, but it's\nhard to say whether it's the board's fault or something else; however,\nif I decompress the troubled file and recompress it without the board,\nthe icon usually reappears. Because of the above mentioned licensing\nproblem, the freeware expansion utility DD Expand will not decompress\na board-compressed file unless you have the board installed.\n\nSince Stac has its own product now, it seems unlikely that the holes\nin Autodoubler/Diskdoubler related to the board will be fixed.\nWhich is sad, and makes me very reluctant to buy Stac's product since\nthey're being so stinky. (But hey, that's competition.)\n-- ",
 'I have a line on a Ducati 900GTS 1978 model with 17k on the clock.  Runs\nvery well, paint is the bronze/brown/orange faded out, leaks a bit of oil\nand pops out of 1st with hard accel.  The shop will fix trans and oil \nleak.  They sold the bike to the 1 and only owner.  They want $3495, and\nI am thinking more like $3K.  Any opinions out there?  Please email me.\nThanks.  It would be a nice stable mate to the Beemer.  Then I\'ll get\na jap bike and call myself Axis Motors!\n\n-- \n-----------------------------------------------------------------------\n"Tuba" (Irwin)      "I honk therefore I am"     CompuTrac-Richardson,Tx\nirwin@cmptrc.lonestar.org    DoD #0826          (R75/6)',
 '\nYep, that\'s pretty much it. I\'m not a Jew but I understand that this is the\nJewish way of thinking. However, the Jews believe that the Covenant between\nYHWH and the Patriarchs (Abraham and Moses, in this case) establishes a Moral\nCode to follow for mankind. Even the Jews could not decide where the boundaries\nfall, though.\n\nAs I understand it, the Sadducees believed that the Torah was all that was\nrequired, whereas the Pharisees (the ancestors of modern Judaism) believed that\nthe Torah was available for interpretation to lead to an understanding of\nthe required Morality in all its nuances (->Talmud).\n\nThe essence of all of this is that Biblical Morality is an interface between\nMan and YHWH (for a Jew or Christian) and does not necessarily indicate\nanything about YHWH outside of that relationship (although one can speculate).\n\n\nThe trouble with all of this is that we don\'t really know what the "created\nin His image" means. I\'ve heard a number of different opinions on this and\nhave still not come to any conclusion. This rather upsets the Apple Cart if\none wants to base a Life Script on this shaky foundation (to mix metaphors\nunashamedly!) As to living by Christ\'s example, we know very little about\nJesus as a person. We only have his recorded utterances in a set of narratives\nby his followers, and some very small references from comtemporary historians.\nRevelation aside, one can only "know" Christ second-hand or worse.\n\nThis is not an attempt to debunk Christianity (although it may seem that way\ninitially), the point I`m trying to make is that we only really have the Bible\nto interpret, and that interpretation is by humanity. I guess this is where\nFaith or Relevation comes in with all its inherent subjectiveness.\n\n\nNo. There may be an absolute moral code. There are undoubtably multiple\nmoral codes. The multiple moral codes may be founded in the absolute moral\ncode. As an example, a parent may tell a child never to swear, and the child\nmay assume that the parent never swears simply because the parent has told\nthe child that it is "wrong". Now, the parent may swear like a trooper in\nthe pub or bar (where there are no children). The "wrongness" here is if\nthe child disobeys the parent. The parent may feel that it is "inappropriate"\nto swear in front of children but may be quite happy to swear in front of\nanimals. The analogy does not quite hold water because the child knows that\nhe is of the same type as the parent (and may be a parent later in life) but\nyou get the gist of it? Incidentally, the young child considers the directive\nas absolute until he gets older (see Piaget) and learns a morality of his own.\n\nDavid.\n\n---\nOn religion:',
 '--\n',
 '\n   {Description of "External Tank" option for SSF redesign deleted}\n\n\nYo Ken, let\'s keep on-top of things! Both the "External Tank" and\n"Wingless Orbiter" options have been deleted from the SSF redesign\noptions list. Today\'s (4/23) edition of the New York Times reports\nthat O\'Connor told the panel that some redesign proposals have\nbeen dropped, such as using the "giant external fuel tanks used\nin launching space shuttles," and building a "station around\nan existing space shuttle with its wings and tail removed."\n\nCurrently, there are three options being considered, as presented\nto the advisory panel meeting yesterday (and as reported in\ntoday\'s Times).\n\nOption "A" - Low Cost Modular Approach\nThis option is being studied by a team from MSFC. {As an aside,\nthere are SSF redesign teams at MSFC, JSC, and LaRC supporting\nthe SRT (Station Redesign Team) in Crystal City. Both LeRC and\nReston folks are also on-site at these locations, helping the respective\nteams with their redesign activities.} Key features of this\noption are:\n  -  Uses "Bus-1", a modular bus developed by Lockheed that\'s\n     qualified for STS and ELV\'s. The bus provides propulsion, GN&C\n     Communications, & Data Management. Lockheed developed this\n     for the Air Force.\n  -  A "Power Station Capability" is obtained in 3 Shuttle Flights.\n     SSF Solar arrays are used to provide 20 kW of power. The vehicle\n     flies in an "arrow mode" to optimize the microgravity environment.\n     Shuttle/Spacelab missions would utilize the vehilce as a power\n     source for 30 day missions.\n  -  Human tended capability (as opposed to the old SSF sexist term\n     of man-tended capability) is achieved by the addition of the\n     US Common module. This is a modified version of the existing\n     SSF Lab module (docking ports are added for the International\n     Partners\' labs, taking the place of the nodes on SSF). The\n     Shuttle can be docked to the station for 60 day missions.\n     The Orbiter would provide crew habitability & EVA capability.\n  -  International Human Tended. Add the NASDA & ESA modules, and\n     add another 20 kW of power\n  -  Permanent Human Presence Capability. Add a 3rd power module,\n     the U.S. habitation module, and an ACRV (Assured Crew Return\n     Vehicle).\n\nOption "B" - Space Station Freedom Derived\nThe Option "B" team is based at LaRC, and is lead by Mike Griffin.\nThis option looks alot like the existing SSF design, which we\nhave all come to know and love :)\n\nThis option assumes a lightweight external tank is available for\nuse on all SSF assembly flights (so does option "A"). Also, the \nnumber of flights is computed for a 51.6 inclination orbit,\nfor both options "A" and "B".\n\nThe build-up occurs in six phases:\n  -  Initial Research Capability reached after 3 flights. Power\n     is transferred from the vehicle to the Orbiter/Spacelab, when\n     it visits.\n  -  Man-Tended Capability (Griffin has not yet adopted non-sexist\n     language) is achieved after 8 flights. The U.S. Lab is\n     deployed, and 1 solar power module provides 20 kW of power.\n  -  Permanent Human Presence Capability occurs after 10 flights, by\n     keeping one Orbiter on-orbit to use as an ACRV (so sometimes\n     there would be two Orbiters on-orbit - the ACRV, and the\n     second one that comes up for Logistics & Re-supply).\n  -  A "Two Fault Tolerance Capability" is achieved after 14 flights,\n     with the addition of a 2nd power module, another thermal\n     control system radiator, and more propulsion modules.\n  -  After 20 flights, the Internationals are on-board. More power,\n     the Habitation module, and an ACRV are added to finish the\n     assembly in 24 flights.\n\nMost of the systems currently on SSF are used as-is in this option, \nwith the exception of the data management system, which has major\nchanges.',
 "Reduced Prices! \nI have a list of things forsale on behalf of my brother, who's moving (moved\nalready)\n\n\t\t\t\t\t\t\t\tOffer:\n1) Black and Decker Duster Plus (Portable Hand Vaccum)\t\n \tpurchased for $32, \t\t\t\t\t  $12\n\n2) SR-1000 Dual Cassette Portable Player, AM/FM\n5-Band graphics Equalizer, high speed dubing, Duo \nTape.Tape deck A, seems to have lost treble sound. \nBut, I bet  it's fixable.\n\tpurchased for $80\t\t\t\t\t  $25\n\n3)Monolux Zoom MicroScope, up to 1200X magnification\nMade in Japan, includes case and accessories\n\tpurchased for $50\t\t\t\t\t  $20\n\n4)Sunbeam 1400 Hair Dryer, the dryer you put your \nhead under/into. You know, the ones you see in the salons.\n(Don't ask me why my bro had it)\n\tpurchased for $60\t\t\t\t          $24\n\n5)Everylast Speed Bag, all leather. Brand new, never \nused\t\t\t\t\t\t\t\t  $10\n\n6)Osterizer Pusle Matic Blender, with 10 speeds \nand a cookbook, 5 years old\t\t\t\t\t  $10\n\tpurchased for $50\n\n8)Binolux Binoculars . 7x35, extra wide angle\n525ft. at 1000yds. with case. very new.\t\t                  $20\n\n9)Proctor and Silex Spray,Steam and Dry Iron.\nvery new.\t\t\t\t\t\t\t  $10\n\n\nAny questions, contact me thru e-mail and I will reply expeditously\nAnd always, S+H are not included, so please consider this.\n\nAnd lastly, I'm a very reasonable.Very Reasonable.",
 '\nDon\'t be so sure.  Look what happened to Japanese citizens in the US during\nWorld War II.  If you\'re prepared to say "Let\'s round these people up and\nstick them in a concentration camp without trial", it\'s only a short step to\ngassing them without trial.  After all, it seems that the Nazis originally\nonly intended to imprison the Jews; the Final Solution was dreamt up partly\nbecause they couldn\'t afford to run the camps because of the devastation\ncaused by Goering\'s Total War.  Those who weren\'t gassed generally died of\nmalnutrition or disease.\n',
 '\nI certainly do use it whenever I have to do TIFF, and it usually works\nvery well.  That\'s not my point.  I\'m >philosophically< opposed to it\nbecause of its complexity.\n\nThis complexity has led to some programs\' poor TIFF writers making\nsome very bizarre files, other programs\' inability to load TIFF\nimages (though they\'ll save them, of course), and a general\ninability to interchange images between different environments\ndespite the fact they all think they understand TIFF.\n\nAs the saying goes, "It\'s not me I\'m worried about- it\'s all the\nabuse of TIFF over the years, and I chalk it all up to the immense (and\nunnecessary) complexity of the format.\n\nIn the words of the TIFF 5.0 spec, Appendix G, page G-1 (capitalized\nemphasis mine):\n\n"The only problem with this sort of success is that TIFF was designed\nto be powerful and flexible, at the expense of simplicity.  It takes a\nfair amount of effort to handle all the options currently defined in\nthis specification (PROBABLY NO APPLICATION DOES A COMPLETE JOB),\nand that is currently the only way you can be >sure< that you will be\nable to import any TIFF image, since there are so many\nimage-generating applications out there now."\n\n\nIf a program (or worse all applications) can\'t read >every< TIFF\nimage, that means there are some it won\'t- some that I might have to\ndeal with.  Why would I want my images to be trapped in that format?  I\ndon\'t and neither should anyone who agrees with my reasoning- not\nthat anyone does, of course! :-)',

In [ ]:
#Create Document Term Matrix | BOW
from sklearn.feature_extraction.text import CountVectorizer

tf_vectorizer = CountVectorizer(stop_words='english', #Stopwords
                               lowercase=True, # Normalization
                               token_pattern= r'\b[a-zA-Z]{3,}', #Tokenization - All words must be greater than equal to 3 a-zAZ
                                strip_accents='unicode' #Trims all unicode chars which is not a part of eng language
                               )

tfObject = tf_vectorizer.fit_transform(docs_raw)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
print(tfObject.shape)

(11314, 69123)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
#Create TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer

tfidfVectorizer = TfidfVectorizer()
tfidfObject = tfidfVectorizer.fit_transform(docs_raw)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
print(tfidfObject.shape)

(11314, 101631)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
#Apply LDA to create topic clusters for Bag of Words

from sklearn.decomposition import LatentDirichletAllocation
lda_tf = LatentDirichletAllocation(n_components=20 , random_state=0)
lda_tf.fit(tfObject) # as per books passing BOW

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

LatentDirichletAllocation(n_components=20, random_state=0)

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation
lda_tfIDF = LatentDirichletAllocation(n_components=10 , random_state=0)
lda_tfIDF.fit(tfidfObject) # as per seasoned DS considering memory optimizn reqd for handling Bigdata

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

LatentDirichletAllocation(random_state=0)

In [ ]:
#Visualizing the LDA model
import pyLDAvis
import pyLDAvis.lda_model
pyLDAvis.enable_notebook()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
#---------------------LDAModel,BOW/TFIDF Object,CountVectorizerObject ----------

pyLDAvis.lda_model.prepare(lda_tf,tfObject,tf_vectorizer)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
13    -0.136405 -0.134240       1        1  11.177020
17    -0.168908  0.085057       2        1  10.959020
1     -0.046179 -0.235285       3        1   9.754624
7     -0.119502  0.161340       4        1   7.871093
18    -0.089559  0.127972       5        1   7.487904
4     -0.120292  0.080361       6        1   6.515381
19    -0.123589  0.078183       7        1   5.595604
9     -0.017531 -0.079746       8        1   5.277798
8     -0.024555  0.137862       9        1   4.709385
16    -0.082000 -0.076504      10        1   4.543653
15    -0.069984 -0.112098      11        1   4.325003
5     -0.060681  0.046393      12        1   3.653814
6     -0.033425 -0.143641      13        1   3.645631
0     -0.032135  0.024478      14        1   3.514086
3      0.203495  0.106076      15        1   2.646846
12     0.016819 -0.033275      16        1   2.525418
11     0.086233 -0.036642      17        1   1.625318
2      0.348730  0.018365      18        1   1.437453
10     0.247438  0.035970      19        1   1.382547
14     0.222029 -0.050626      20        1   1.352402, topic_info=              Term         Freq        Total Category  logprob  loglift
36161          max  3850.000000  3850.000000  Default  30.0000  30.0000
23693          god  1901.000000  1901.000000  Default  29.0000  29.0000
31729          key  1130.000000  1130.000000  Default  28.0000  28.0000
55783        space  1208.000000  1208.000000  Default  27.0000  27.0000
20819         file  1680.000000  1680.000000  Default  26.0000  26.0000
...            ...          ...          ...      ...      ...      ...
45070      picture    32.856824   193.287040  Topic20  -6.0055   2.5313
2799   application    35.384507   448.836376  Topic20  -5.9313   1.7629
63434          uww    24.774501    93.573905  Topic20  -6.2878   2.9744
38284        model    28.011121   359.364937  Topic20  -6.1650   1.7516
53680          set    28.564434   970.135189  Topic20  -6.1455   0.7780

[1467 rows x 6 columns], token_table=       Topic      Freq          Term
term
197        5  0.025929           abs
197       10  0.025929           abs
197       11  0.051859           abs
197       14  0.025929           abs
197       17  0.855667           abs
...      ...       ...           ...
68227     20  0.003731          york
68274     20  0.879802           ypg
68329     19  0.863353           yub
68691      9  0.964716       zionist
68885     12  0.952624  zoroastrians

[5793 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[14, 18, 2, 8, 19, 5, 20, 10, 9, 17, 16, 6, 7, 1, 4, 13, 12, 3, 11, 15])

In [ ]:
pyLDAvis.lda_model.prepare(lda_tfIDF,tfidfObject,tfidfVectorizer)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
4     -0.318304 -0.000030       1        1  80.971314
5      0.038501 -0.013710       2        1   2.465201
2      0.038020  0.012015       3        1   2.398317
0      0.036992  0.000800       4        1   2.265946
3      0.035307  0.000256       5        1   2.139385
1      0.034782  0.000181       6        1   2.058676
8      0.034399  0.000073       7        1   2.007379
6      0.034383  0.000153       8        1   2.002399
7      0.033203  0.000449       9        1   1.869226
9      0.032718 -0.000187      10        1   1.822157, topic_info=             Term        Freq       Total Category  logprob  loglift
88532         the  938.000000  938.000000  Default  30.0000  30.0000
89360          to  542.000000  542.000000  Default  29.0000  29.0000
67670          of  458.000000  458.000000  Default  28.0000  28.0000
18521         and  416.000000  416.000000  Default  27.0000  27.0000
51136          is  365.000000  365.000000  Default  26.0000  26.0000
...           ...         ...         ...      ...      ...      ...
68026        omar    0.122325    0.462642  Topic10  -9.3715   2.6749
6905          3ds    0.122704    0.493569  Topic10  -9.3684   2.6133
50541  interleave    0.118767    0.470080  Topic10  -9.4010   2.6294
27818    clearify    0.108905    0.403011  Topic10  -9.4877   2.6967
12320        8051    0.108563    0.649498  Topic10  -9.4909   2.2163

[420 rows x 6 columns], token_table=        Topic      Freq                                               Term
term
14749       1  0.581254  ______________________________________________...
18521       1  1.000334                                                and
19443       1  1.001299                                                are
19756       1  1.001942                                                 as
20123       1  0.997530                                                 at
20803      10  0.624274                                                 ax
21572       1  0.626774                                              banks
21572       6  0.208925                                              banks
21987       1  0.999188                                                 be
24804       1  1.001895                                                but
25376       6  1.102093                                              cadre
25590       1  0.997000                                                can
26826       6  1.122119                                           chastity
32658       1  0.976417                                           deletion
34355       1  0.554484                                              ditto
35266       6  1.124025                                                dsl
41127       1  1.000732                                                for
41715       1  1.000533                                               from
42935       6  0.946125                                                geb
44002       1  0.700353                                             gordon
44002       6  0.233451                                             gordon
45885       1  0.999327                                               have
48754       1  1.000146                                                 if
49447       1  1.000820                                                 in
50415       6  1.013424                                          intellect
51136       1  1.000258                                                 is
51326       1  1.000604                                                 it
54004       1  0.870910                                           keywords
57335       1  0.770759                                           logitech
57464       8  1.163071                                              loser
64435       1  0.997024                                                 my
64699       6  1.122119                                              n3jxp
66511       1  0.999224                                                not
67670       1  1.000336                                                 of
68080       1  0.997683                                                 on
68409       1  1.001438                                                 or
71556       1  0.790998                                                pit
71579       1  0.680505                                               pitt
71579       6  0.226835                                               pitt
75261       1  0.823444                                                que
82021       6  1.069821                                           shameful
83068       1  0.455680                                         skepticism
83068       6  0.911361                                         skepticism
83938       1  0.940973                                               soon
83938       6  0.062732                                               soon
85911       1  0.713818                                                 su
86628       1  0.503119                                          surrender
86628       6  0.251560                                          surrender
88519       1  1.000023                                               that
88532       1  0.999672                                                the
88638       1  1.001377                                              there
88694       1  0.999472                                               they
88767       1  1.001018                                               this
89360       1  0.999510                                                 to
95844       1  0.999846                                                was
96391       1  1.002381                                               what
96917       1  1.001099                                               with
97332       1  1.000777                                              would
98150       1  1.084516                                            xarchie
100208      1  0.998842                                                you, R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[5, 6, 3, 1, 4, 2, 9, 7, 8, 10])

In [ ]:
# Assign label to each text data

import pandas as pd

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
#Transform all document using the trained model
topicData = lda_tfIDF.transform(tfidfObject)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
#Select the topic with highest frequncy

labels = topicData.argmax(axis=1)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
finalDF = pd.DataFrame({
    'data': docs_raw,
    'label' : labels
})

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
finalDF.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                                                data  label
0  I was wondering if anyone out there could enli...      4
1  A fair number of brave souls who upgraded thei...      4
2  well folks, my mac plus finally gave up the gh...      4
3  \nDo you have Weitek's address/phone number?  ...      4
4  From article <C5owCB.n3p@world.std.com>, by to...      4

In [ ]:
finalDF.label.value_counts()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

label
4    10865
0      322
9       25
2       21
1       19
5       17
3       15
6       13
7       10
8        7
Name: count, dtype: int64